### PR TITLE
Fix data models docs

### LINKED ISSUE #3: Research Date Ranges
Double checking the 13 month time period (01-08-21 - 31-08-22) is correct and not supposed to be 12 months

https://github.com/MattStammers/hdruk_avoidable_admissions_collaboration_docs/blob/main/docs/index.md?plain=1#L34

### LINKED ISSUE #6: Data Model Issues
@MattStammers , the data specification documentation could use some love - broken urls, variable names that could do with truncating and one typo. I have created a PR for this.

### PR DESCRIPTION
**Pull request by vvcb**
@MattStammers , I have made some variable name changes (truncated a few, fixed typo in one and lowercased another). I have also fixed the URLs linking to the NHS Data Dictionary.  This fixes #6.

The code in <https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/data/validate.py> already reflects these changes. 

I have also corrected the date ranges for the study period. This fixes #3.

### CODE REVIEW

**Comment by MattStammers** [comment]
Thanks for changing the dates @vvcb

**Comment by vvcb** [comment]
@MattStammers  - see email trail today regarding dates. The date range in the Google Docs is different from what @RicCampbell has recommended in #3 .

**Review by MattStammers — APPROVED** [review]
Dates and columns fixed

**Comment by vvcb** [comment]
@MattStammers  - Looks like we need a second reviewer to approve before merging this PR. :-)

**Review by ccarenzoIC — APPROVED** [review]

**Comment by MattStammers** [comment]
Thanks @ccarenzoIC

**Pull request merged**
